import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'${inter.className} bg-gradient-to-r from-blue-300 to-blue-900 text-2xl'}>{children}</body>
    <footer className="text-center">hello</footer>
    </html>
  )
}

