import { Inter } from 'next/font/google'
import './globals.css'
//import { Analytics } from '@vercel/analytics/react'
import '@radix-ui/themes/styles.css';

import { Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <Theme>
  <body className={`${inter.className} bg-gradient-to-r from-blue-300 to-blue-900 flex flex-col min-h-screen text-2xl`}>
    {children}
  
  </body>
  <ThemePanel />
</Theme>
      <footer className="text-center">
      <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:justify-between">
      <span className="text-sm text-black bold sm:text-center">© 2023 <a href="#" className="hover:underline text-black bold">CSCI-25™</a>. All
        Rights Reserved.
      </span>
      <ul className="flex flex-wrap items-center mt-3 text-sm font-medium text-black bold sm:mt-0">
        <li>
          <a href="#" className="mr-4 hover:underline md:mr-6 ">About</a>
        </li>
        <li>
          <a href="#" className="mr-4 hover:underline md:mr-6">Privacy Policy</a>
        </li>
        <li>
          <a href="#" className="mr-4 hover:underline md:mr-6">Licensing</a>
        </li>
        <li>
          <a href="#" className="hover:underline">Contact</a>
        </li>
      </ul>
    </div>
      </footer>
    </html>
  )
}
